version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql.txt
    image: mysql-from-compose
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root1
   
  wordpress:
    depends_on:
      - db
    image: arikperl/wordpress:5.2.2-wc-3.5.3-ioncube
    ports:
      - "7777:80"
    volumes: 
       - ../WP-repos/wp-baseline:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
    container_name: wp-1

