FROM arikperl/wordpress:4.9.9
COPY wp-config.php /var/www/html/
ENV WOOCOMMERCE_VERSION 3.5.3
ENV WOOCOMMERCE_UPSTREAM_VERSION 3.5.3

RUN apt-get update
RUN apt-get install -y --no-install-recommends unzip wget

RUN wget https://downloads.wordpress.org/plugin/woocommerce.${WOOCOMMERCE_VERSION}.zip -O /tmp/temp.zip \
    && cd /usr/src/wordpress/wp-content/plugins \
    && unzip /tmp/temp.zip \
    && rm /tmp/temp.zip
